AWSTemplateFormatVersion: '2010-09-09'
Description: Web Crawler Application

Parameters:
  S3Bucket:
    Description: S3 bucket name for the Lambda function code
    Type: String

Resources:
  PriceHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PriceHistory
      AttributeDefinitions:
        - AttributeName: ProductId
          AttributeType: S
        - AttributeName: Timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: ProductId
          KeyType: HASH
        - AttributeName: Timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  WebCrawlerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: WebCrawlerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt PriceHistoryTable.Arn
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub arn:aws:s3:::${S3Bucket}/*

  WebCrawlerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: WebCrawler
      Runtime: python3.9
      Handler: app.handler
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: app.py.zip
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref PriceHistoryTable
      Role: !GetAtt WebCrawlerFunctionRole.Arn
      Timeout: 300
      MemorySize: 256

  WebCrawlerScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule for Web Crawler Lambda Function"
      ScheduleExpression: "rate(12 hours)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt WebCrawlerFunction.Arn
          Id: "WebCrawlerSchedule"

  WebCrawlerSchedulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebCrawlerFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt WebCrawlerScheduleRule.Arn

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt WebCrawlerFunction.Arn
  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref PriceHistoryTable