org: aturo
app: sentinel
service: sentinel

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
  environment:
    SENDER_EMAIL: ${env:SENDER_EMAIL}
    RECIPIENT_EMAIL: ${env:RECIPIENT_EMAIL}
    DEFAULT_AWS_REGION: us-east-1

functions:
  webScraper:
    handler: handler.handler
    events:
      - schedule: cron(0 0 * * ? *) 

resources:
  Resources:
    PricesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: prices
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1